version: '3'

services:
  app:
    image: 'baddads/admin'
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
      - '5005:5005'
    depends_on:
      - db

  db:
    environment:
      - POSTGRES_USER=baddads
      - POSTGRES_PASSWORD=baddads
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    container_name: postgresql
    image: postgres
